### ISSUE TITLE
How can I create environment file ?

### ISSUE THREAD

**Issue by Any0ne22** [elibolonur/ts-express-vuejs#5]
I'm not able to use environment files with Vue, I created `.env` file at the root of the project and I can only access to my vars in the server code using `process.env` and not in the Vue code (I can only access to `process.env.NODE_ENV`)
What am I doing wrong ?

**Comment by elibolonur** [comment]
Vue side of project is using `vue-cli-service`, that said the cli loads only variables that start with VUE_APP_ to the client project.

Details:
https://cli.vuejs.org/guide/mode-and-env.html

So any variable you define without `VUE_APP_` prefix will be accessible on the server project but not the client project.
